name: 'Nu HTML Checker'
description: 'Validates an URL for HTML errors'
inputs:
  url:
    description: 'URL to validate'
    required: true
outputs:
  errors-count:
    description: 'The amount of validation errors found'
  report-url:
    description: 'URL to the report'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: npx playwright install --with-deps chromium
      shell: bash
    - run: node dist/index.js
      shell: bash
