name: 'Nu HTML Checker'
description: 'Validates an URL for HTML errors'
inputs:
  url:
    description: 'URL to validate'
    required: true
outputs:
  ERROR_COUNT:
    description: 'The amount of validation errors found'
  REPORT_URL:
    description: 'URL to the report'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - run: npx playwright install --with-deps chromium
      shell: bash
    - run: node ${GITHUB_ACTION_PATH}/dist/index.js
      shell: bash
