on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to validate'
        type: string
        required: true
        default: 'https://example.com'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test action
        uses: ./
        id: test
        with:
          url: 'https://example.com'
      - name: Echo outputs
        shell: bash
        run: |
          echo "ERROR COUNT: ${{ steps.test.outputs.error-count }}"
          echo "REPORT URL: ${{ steps.test.outputs.report-url }}"
