on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL to validate'
        type: string
        required: true
        default: 'https://example.com'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test action
        uses: ./
